# Define the goal
# Common waypoint details
cola2_msgs/GoalDescriptor goal

# If true, maintain Z position relative to altitude, otherwise depth.
bool altitude_mode

cola2_msgs/NED position
float32 altitude
cola2_msgs/RPY orientation

# Axes of control to disable, in body frame.
# * for GOTO X-Z-YAW enable x and z
# * for Holonomic goto: enable x, yaw and z
cola2_msgs/Bool6Axis disable_axis

# Tolerances are in body frame, zero indicates pilot default should be used.
geometry_msgs/Vector3 position_tolerance
cola2_msgs/RPY orientation_tolerance

# Velocity. WARNING! Right now only linear_velocity.x is used!
geometry_msgs/Vector3 linear_velocity
cola2_msgs/RPY angular_velocity

# Controller type
uint8 controller_type
uint8 GOTO=0       # Controls z, yaw and surge
uint8 HOLONOMIC_GOTO=1  # Controls x, y, z and yaw
uint8 ANCHOR=2 # to keep position with non holonomic vehicles

# Max time to achieve waypoint. If timeout <= 0, time is infinite.
int16 timeout

# Is a keep position request?
bool keep_position
---

# Define the result
# If true, maintain Z position relative to altitude, otherwise depth.
bool altitude_mode

cola2_msgs/NED position
float32 altitude
cola2_msgs/RPY orientation

uint8 final_status
uint8 SUCCESS=0
uint8 TIMEOUT=1
uint8 FAILURE=2
uint8 BUSY=3
---

# Define a feedback message
# If true, maintain Z position relative to altitude, otherwise depth.
bool altitude_mode
cola2_msgs/NED position
float32 altitude
cola2_msgs/RPY orientation
float64 distance_to_waypoint
