geometry_msgs/Vector3 position
float32 yaw
float32 altitude
bool altitude_mode

# If blocking is True, server do not returns until waypoint reached (blocking the thread from which it is called)
bool blocking

# If keep_position is True, the timeout is set to a large number and the goto only finalizes when it is canceled
bool keep_position

uint8 priority

uint8 REFERENCE_NED=0
uint8 REFERENCE_GLOBAL=1
uint8 REFERENCE_VEHICLE=2
uint8 reference

# GOTO:             False,  True,   ?,      True,   True,   False
# HOLONOMIC GOTO:   False,  False,  ?,      True,   True,   ?
# SUBMERGE:         True,   True,   False,  True,   True,   True
cola2_msgs/Bool6Axis disable_axis

geometry_msgs/Vector3 position_tolerance
cola2_msgs/RPY orientation_tolerance

geometry_msgs/Vector3 linear_velocity
cola2_msgs/RPY angular_velocity

# Max timeout to reach position in seconds. If a more restrictive one is
# computed by the captain using distance and velocity, it will override this one.
# If keep_position is true, timeout is the time to keep position.
float64 timeout

---
bool success
string message
